### ISSUE TITLE
proxies

### ISSUE THREAD

**Issue by slush-byte** [ramnetos/RamOS#21]
none of the proxies work(either broken or blocked). Thank you for all your hard wark tho in this website. Js letting the wonderful team know. - thank you for your time

**Comment by DJshelfmushroom** [comment]
yeah we know ): try [dragon731021/cauDNS](https://github.com/dragon731012/cauDNS)

**Comment by DJshelfmushroom** [comment]
also use discussions for this kinda stuff

**Comment by slush-byte** [comment]
thx but how does it run tho. im on home wifi btw. its typed into the bar but nothing happens after. i made a mistake maybe? idk man pls help

**Comment by DJshelfmushroom** [comment]
your school prob has bookmarklets blocked. go to the [website](https://caudns.vercel.app/).
if that's blocked,
Go to chrome://network#state
find the wifi you are connected to (or want to block).
Press the plus by it, and copy everything inside the box that just showed up.
put it in here and I'll do it for u

**Comment by slush-byte** [comment]
thx man its
{
	"Connectable": true,
	"ConnectionState": "Connected",
	"ErrorState": "disconnect-failure",
	"GUID": "7496427b-69ed-4eae-a344-a7c739ffec73",
	"IPAddressConfigType": "DHCP",
	"IPConfigs": [
		{
			"Gateway": "10.0.0.1",
			"IPAddress": "10.0.0.136",
			"NameServers": [
				"75.75.75.75",
				"75.75.76.76"
			],
			"RoutingPrefix": 24,
			"Type": "IPv4",
			"WebProxyAutoDiscoveryUrl": ""
		},
		{
			"Gateway": "fe80::e6bf:faff:fe90:cfc6",
			"IPAddress": "2601:2c1:8800:d9a0:1a57:799e:231d:5afc",
			"NameServers": [
				"2001:558:feed::1",
				"2001:558:feed::2"
			],
			"RoutingPrefix": 64,
			"Type": "IPv6",
			"WebProxyAutoDiscoveryUrl": ""
		}
	],
	"MacAddress": "30:05:05:F3:F8:9F",
	"Metered": false,
	"Name": "HD Home5",
	"NameServersConfigType": "DHCP",
	"Priority": 0,
	"SavedIPConfig": {
		"Gateway": "10.0.0.1",
		"IPAddress": "10.0.0.136",
		"NameServers": [
			"75.75.75.75",
			"75.75.76.76"
		],
		"RoutingPrefix": 24,
		"Type": "IPv4"
	},
	"Source": "User",
	"TrafficCounterResetTime": 0,
	"Type": "WiFi",
	"WiFi": {
		"AllowGatewayARPPolling": true,
		"AutoConnect": true,
		"BSSID": "e6:bf:fa:98:cf:c9",
		"BSSIDAllowlist": [],
		"BSSIDRequested": "",
		"EAP": {
			"AnonymousIdentity": "",
			"DomainSuffixMatch": [],
			"Identity": "",
			"SaveCredentials": true,
			"SubjectAlternativeNameMatch": [],
			"SubjectMatch": "",
			"TLSVersionMax": "",
			"UseProactiveKeyCaching": false,
			"UseSystemCAs": true
		},
		"Frequency": 5220,
		"FrequencyList": [
			5220
		],
		"HexSSID": "484420486F6D6535",
		"HiddenSSID": false,
		"PasspointId": "",
		"PasspointMatchType": "",
		"SSID": "HD Home5",
		"Security": "WPA-PSK",
		"SignalStrength": 82,
		"SignalStrengthRssi": -52
	}
}

**Comment by DJshelfmushroom** [comment]
[network.zip](https://github.com/user-attachments/files/17267234/network.zip)

**Comment by DJshelfmushroom** [comment]
extract the zip, go to chrome://network, then "import network" at the bottom.  go into your extracted folder and open "kill.onc"

**Comment by slush-byte** [comment]
thx but the zip shows 
![image](https://github.com/user-attachments/assets/758dce93-943e-4224-9b88-3e43ab796571)

**Comment by DJshelfmushroom** [comment]
huh what? send a screen recording plz

**Comment by slush-byte** [comment]
yea gimme 1 sec

**Comment by DJshelfmushroom** [comment]
if you join the [slack](https://join.slack.com/t/ramnetworksmi/shared_invite/zt-2ry5eticl-8_dYU5ZBcwjlKNrTMrPQ_A) I can prob help u better there

**Comment by slush-byte** [comment]
[Screen recording 2024-10-05 2.31.03 PM.webm](https://github.com/user-attachments/assets/e2e01420-8c75-4ba4-ade0-67866b7e94dc)

**Comment by DJshelfmushroom** [comment]
click the link on the zip?

**Comment by slush-byte** [comment]
yup
idk why it does this

**Comment by DJshelfmushroom** [comment]
see if u can join the slack (its probable blocked)

**Comment by slush-byte** [comment]
yea its blocked

**Comment by DJshelfmushroom** [comment]
k. create a new file anywhere, name it kill.txt. paste this in and then rename it to kill.onc:
like this: 
[Screen recording 2024-10-05 12.36.51 PM.webm](https://github.com/user-attachments/assets/7de43548-cb54-476b-b36b-8bbce5810d24)



{"Type":"UnencryptedConfiguration","NetworkConfigurations":[{"GUID":"7496427b-69ed-4eae-a344-a7c739ffec73","Metered":true,"Name":"HD Home5","Type":"WiFi","WiFi":{"AutoConnect":true,"SSID":"HD Home5","Security":"None"},"NameServersConfigType":"Static","StaticIPConfig":{"NameServers":["38.175.197.10","66.94.105.229","213.109.163.210","92.60.37.102"]},"ProxySettings":{"Type":"Direct"}}]}

**Comment by slush-byte** [comment]
whats the revive one for tho

**Comment by slush-byte** [comment]
thx btw but js curious

**Comment by slush-byte** [comment]
also what do i do after it shows this 
![image](https://github.com/user-attachments/assets/6b04461e-518d-4e04-8617-31cf44373d7d)

**Comment by slush-byte** [comment]
u there?

**Comment by DJshelfmushroom** [comment]
its just to undo it if it breaks something

**Comment by slush-byte** [comment]
what do i do after its imported tho?

**Comment by slush-byte** [comment]
and pls pls pls send revive incase something breaks

**Comment by DJshelfmushroom** [comment]
oh you just turn wifi off and on and you're done. to revive, go into your wifi settings andthe network you blocked then scroll down to "network" and switch to automatic name servers

**Comment by DJshelfmushroom** [comment]
did it work tho?

**Comment by slush-byte** [comment]
[Screen recording 2024-10-05 7.01.43 PM.webm](https://github.com/user-attachments/assets/03cdffad-502d-4761-a09f-a5006c74f40d)
what i do wrong???

**Comment by DJshelfmushroom** [comment]
i cant tell. if you record just a window all i see is that window

**Comment by DJshelfmushroom** [comment]
oh. did you enable and disable wifi?

**Comment by DJshelfmushroom** [comment]
check my comment [here](https://github.com/dragon731012/cauDNS/issues/21)

**Comment by DJshelfmushroom** [comment]
and it might not work with ck express

**Comment by slush-byte** [comment]
[Screen recording 2024-10-05 7.19.35 PM.webm](https://github.com/user-attachments/assets/3965f613-a35e-49aa-80c7-65aec97dbab5)
it may not work for ck express tho 
got any others?

**Comment by slush-byte** [comment]
nah dude

**Comment by DJshelfmushroom** [comment]
it doesn't look like the name servers imported. one sec.

**Comment by DJshelfmushroom** [comment]
manually set the name servers to:
38.175.197.10
66.94.105.229
213.109.163.210 
92.60.37.102

**Comment by slush-byte** [comment]
![image](https://github.com/user-attachments/assets/13c6c726-959c-49f0-a99a-b60e9ab6ba13)
what i do now

**Comment by DJshelfmushroom** [comment]
turn wifi off-on and see if it worked

**Comment by slush-byte** [comment]
![image](https://github.com/user-attachments/assets/76c36f3a-26d6-400b-97b5-37eb95456600)
stupid ahh ck js initailizing

**Comment by DJshelfmushroom** [comment]
ok dont think it works, set it back to automatic, ill brb

**Comment by slush-byte** [comment]
yea thx man

**Comment by DJshelfmushroom** [comment]
can you get the extension "chromebook recovery utility?

**Comment by slush-byte** [comment]
lemme see

**Comment by DJshelfmushroom** [comment]
prob not

**Comment by slush-byte** [comment]
yea nope

**Comment by DJshelfmushroom** [comment]
ok well i dont think I have anything else for u unless you have a personal computer

**Comment by slush-byte** [comment]
yea nah

**Comment by slush-byte** [comment]
but thx for all the help man

**Comment by DJshelfmushroom** [comment]
yeah np man

**Comment by slush-byte** [comment]
js one last thing

**Comment by DJshelfmushroom** [comment]
ooh one more thing:
crazygames.fr

**Comment by DJshelfmushroom** [comment]
crazygames but _france_

**Comment by slush-byte** [comment]
got any link dispensers
(crazygames blocked too ):  
)

**Comment by DJshelfmushroom** [comment]
link dispensers?

**Comment by slush-byte** [comment]
yea

**Comment by DJshelfmushroom** [comment]
wuz that

**Comment by slush-byte** [comment]
like it makes links for like doge art class, that type of stuff

**Comment by DJshelfmushroom** [comment]
no idea what ur talking about

**Comment by slush-byte** [comment]
so you can keep making more links if one gets blocked

**Comment by slush-byte** [comment]
ah

**Comment by DJshelfmushroom** [comment]
ohhhh yea I dont but I use koyeb to deploy

**Comment by slush-byte** [comment]
how does deployment even work

**Comment by DJshelfmushroom** [comment]
you give the thing some code it does some ✨_magic_✨ and now you have a proxy

**Comment by slush-byte** [comment]
GiVe CodE PlEaSeeeEeeEE

**Comment by slush-byte** [comment]
cuz no proxy working over here
with the triple layer gogaurd ck and school internet

**Comment by DJshelfmushroom** [comment]
https://github.com/DogeNetwork/v4

**Comment by DJshelfmushroom** [comment]
fork it then deploy
