### ISSUE TITLE
proxy's are blocked

### ISSUE THREAD

**Issue by Fredd1Graves** [ramnetos/RamOS#23]
Hey the proxys on the website are blocked for contentrestriction, well at least for Northwest isd

**Comment by DJshelfmushroom** [comment]
see pinned issue

**Comment by theshmunguss1** [comment]
Seriously. Follow the guidelines and template for creating an issue. We cannot do anything about a website being blocked, nor unblock it for you. We only condone the circumvention of blocked sites, not interfering with school Wi-Fi and possibly getting in legal trouble.
