### ISSUE TITLE
Blocked

### ISSUE THREAD

**Issue by YesTheProxy** [ramnetos/RamOS#5]
The site was blocked on cisco, we need a new domain.

**Comment by theshmunguss1** [comment]
damn

**Comment by theshmunguss1** [comment]
https://ramnetos.github.io/RamOS/ is the new link, I made a new organization & transferred the repo

**Comment by DJshelfmushroom** [comment]
Not for long

**Comment by theshmunguss1** [comment]
>Not for long

What do you mean by this? It's still working for me.

**Comment by theshmunguss1** [comment]
oops

**Comment by DJshelfmushroom** [comment]
just i mean it will be blocked soon.

**Comment by YesTheProxy** [comment]
Umm Guys... Someone beat us to the OS in browser for unblocking stuff https://clockwork-os.vercel.app/

**Comment by YesTheProxy** [comment]
Oh and a CHATING APP?!?!?!?!? https://muenster-client.vercel.app/

**Comment by DJshelfmushroom** [comment]
both blocked lmao
