### ISSUE TITLE
Two deploy actions taking up run minutes

### ISSUE THREAD

**Issue by DJshelfmushroom** [ramnetos/RamOS#8]
@theshmunguss1 is there a way you could delete "Pages build and deploy"? It is useless and makes deploying take more time. Keep "Better pages deploy"

**Comment by DJshelfmushroom** [comment]
@theshmunguss1

**Comment by theshmunguss1** [comment]
I'm confused how to do this, I don't think I have any control in the Actions tab. Does deploying really take that long for you?

**Comment by DJshelfmushroom** [comment]
yes, and it takes up actions minutes.

**Comment by DJshelfmushroom** [comment]
maybe screenshare?

**Comment by theshmunguss1** [comment]
alr

**Comment by DJshelfmushroom** [comment]
@theshmunguss1 check slack

**Comment by DJshelfmushroom** [comment]
@theshmunguss1

**Comment by DJshelfmushroom** [comment]
idea:
settings>pages>build and deployment mess around, try and find "static html"
@theshmunguss1

**Comment by theshmunguss1** [comment]
I'm trying a Jekyll deployment but it is taking a while.

**Comment by DJshelfmushroom** [comment]
no don't do jekyll. 1 sec static should be avaliable now.

**Comment by theshmunguss1** [comment]
The action has been running for 5 minutes now.

**Comment by DJshelfmushroom** [comment]
ya delete it

**Comment by theshmunguss1** [comment]
22 minutes now. I don't think a static action will work.

**Comment by theshmunguss1** [comment]
Should I close this issue?

**Comment by DJshelfmushroom** [comment]
no, I deleted it. that's why. go create a static?

**Comment by DJshelfmushroom** [comment]
jekyll isn't static

**Comment by DJshelfmushroom** [comment]
show me?
